name: Flatpak CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "data/**"
      - "types/**"
      - "meson.build"
      - "meson_options.txt"
      - "uz.mohirlab.senbrua.json"
      - ".github/workflows/flatpak.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "data/**"
      - "types/**"
      - "meson.build"
      - "meson_options.txt"
      - "uz.mohirlab.senbrua.json"

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flathub-worker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak
        run: |
          flatpak-builder --repo=repo --disable-rofiles-fuse --force-clean --arch=x86_64 app uz.mohirlab.senbrua.json

      - name: Create bundle
        run: |
          flatpak build-bundle repo senbrua.flatpak uz.mohirlab.senbrua

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: senbrua-flatpak
          path: senbrua.flatpak
