name: Snap CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "data/**"
      - "snap/**"
      - "meson.build"
      - "meson_options.txt"
      - ".github/workflows/snap.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "data/**"
      - "snap/**"
      - "meson.build"
      - "meson_options.txt"

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build gettext gir1.2-gtk-4.0 gir1.2-adw-1 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gir1.2-gst-plugins-bad-1.0 nodejs npm

      - name: Install Snapcraft
        uses: snapcore/action-install-snapcraft@v1
        with:
          channel: stable

      - name: Build Snap
        run: snapcraft --destructive-mode

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: senbrua-snap
          path: "*.snap"
