name: Snap CI

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install snapcraft
        run: sudo snap install --classic snapcraft

      - name: Build Snap
        run: sudo snapcraft pack --destructive-mode

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: senbrua-snap
          path: "*.snap"
